export const iconList =
  ['Badge', 'Ban', 'BarChart', 'BarChart2', 'Battery', 'BatteryCharging', 'Beaker',
    'Bell', 'BellOff', 'BezierCurve', 'Bike', 'Binary', 'Bluetooth', 'Bold', 'Book',
    'BookOpen', 'Bookmark', 'Box', 'Briefcase', 'Calendar', 'Camera', 'CameraOff',
    'Car', 'Cast', 'Check', 'CheckCircle', 'CheckSquare', 'ChevronDown', 'ChevronLeft',
    'ChevronRight', 'ChevronUp', 'Circle', 'Clipboard', 'Clock', 'Cloud', 'CloudDrizzle',
    'CloudLightning', 'CloudOff', 'CloudRain', 'CloudSnow', 'Code', 'Codepen', 'Codesandbox',
    'Coffee', 'Columns', 'Command', 'Compass', 'Copy', 'CornerDownLeft', 'CornerDownRight',
    'CornerLeftDown', 'CornerLeftUp', 'CornerRightDown', 'CornerRightUp', 'CornerUpLeft',
    'CornerUpRight', 'Cpu', 'CreditCard', 'Crop', 'Crosshair', 'Database', 'Delete',
    'Disc', 'Divide', 'DivideCircle', 'DivideSquare', 'DollarSign', 'Download', 'DownloadCloud',
    'Dribbble', 'Droplet', 'Edit', 'Edit2', 'Edit3', 'ExternalLink', 'Eye', 'EyeOff',
    'Facebook', 'FastForward', 'Feather', 'Figma', 'File', 'FileMinus', 'FilePlus',
    'FileText', 'Film', 'Filter', 'Flag', 'Folder', 'FolderMinus', 'FolderPlus', 'Framer',
    'Bell', 'Battery', 'Bluetooth', 'BookOpen', 'Box', 'Briefcase', 'Brush', 'Camera', 'Calendar',
    'Car', 'CheckCircle', 'Cloud', 'Compass', 'CreditCard', 'Crop', 'Database', 'Dice', 'Disc',
    'DollarSign', 'Droplet', 'Edit', 'Eye', 'Feather', 'FileText', 'Filter', 'Flag', 'Flashlight',
    'Flask', 'Folder', 'Gift', 'GitHub', 'Globe', 'Heart', 'Headphones', 'Home', 'Image', 'Inbox',
    'Key', 'Laptop', 'Layers', 'LifeBuoy', 'Lightbulb', 'Link', 'Lock', 'Mail', 'Map', 'MessageSquare',
    'Mic', 'Monitor', 'Moon', 'MousePointer', 'Music', 'Package', 'Paperclip', 'PenTool', 'Phone',
    'PieChart', 'Printer', 'Radio', 'RefreshCcw', 'Rocket', 'Scissors', 'Server', 'Settings', 'Shield',
    'ShoppingBag', 'Smartphone', 'Speaker', 'Star', 'Sun', 'Tablet', 'Tag', 'Target', 'Terminal',
    'Thermometer', 'ThumbsUp', 'Tool', 'Trash', 'Truck', 'Umbrella', 'Upload', 'User', 'Users', 'Video',
    'Volume', 'Watch', 'Wifi', 'Wind', 'ZoomIn', 'ZoomOut'

  ]